name: dotnet

on: [push]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '6.0.415'
      
      - name: build
        run: |
          echo Compilation
          echo off
          cd  C:/Users/runneradmin/AppData/Local/
          mkdir osu!
          mkdir osu!install
          cd osu!install
          echo installing osu!
          choco install wget
          wget http://m2.ppy.sh/r/osu!install.exe
          ren osu!install.exe osu!.exe
          move osu!.exe ../osu!
          cd ../
          mkdir osu!tourney
          choco install
          cd osu!
          xcopy osu!.exe C:\Users\runneradmin\AppData\Local\osu!tourney
          mkdir mappool
          cd mappool
          echo "test" > a.test
          cd ../../osu!tourney
          mkdir Songs
          cd D:/a/osu-tourney-setup/osu-tourney-setup/tourney.main/
          dotnet --version
          dotnet --info
          dotnet --list-runtimes
          dotnet build "osu!tourney-setup.sln" -c Release
          dotnet build "osu!tourney-setup.csproj" -c Release --arch arm64
          dotnet build "osu!tourney-setup.csproj" -c Release --arch x64
          dotnet build "osu!tourney-setup.csproj" -c Release --arch arm64 --os linux
          dotnet build "osu!tourney-setup.csproj" -c Release --arch x64 --os linux
          dotnet run "osu!tourney-setup.sln"
          y




